buildscript {
    repositories {
        maven {
            url "${mavenUrl}"
        }
//        mavenCentral()
//        jcenter()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }
}

apply {
    plugin 'org.springframework.boot'
}

jar {
    baseName = 'hello-spring-boot'
    version = '0.0.1-SNAPSHOT'
}

dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter'

    implementation("org.springframework.boot:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }

    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-jetty'

    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-cache'

    implementation group: 'io.netty', name: 'netty-all', version: '4.1.11.Final'

    implementation 'com.github.ben-manes.caffeine:caffeine'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.7'

    // 编译hello-utils目录下的hello-utils模块
    implementation project(':hello-utils')

    // include junit
    testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test'

}
