spring.profiles.active=dev
server.port=14001

ipip.datax-enabled=true

#org.springframework.boot.autoconfigure.cache.CacheType,or comment this for auto-detect
spring.cache.type=CAFFEINE
SpringCacheable.localCacheableManager.expireAfterWrite=10000
SpringCacheable.localCacheable.expireAfterWrite=1000

management.security.enabled=false
endpoints.shutdown.enabled=true
#endpoints.shutdown.sensitive=false
endpoints.shutdown.path=/shutdown
