spring.profiles.include=secret
#baidu.appid=
#baidu.appkey=
#baidu.secretkey=

spring.thymeleaf.mode=LEGACYHTML5

spring.http.multipart.max-file-size=5MB
logging.level.root=warn
logging.level.iorichina.hellojava.helloface=info<<<<<<< .minelogging.level.root=warn
logging.level.iorichina.hellojava.helloface=info
=======>>>>>>> .theirs